# Generated by Django 4.1.2 on 2022-10-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
